version: '3.8'
services:
  # --- PostgreSQL Service ---
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: User
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: Store
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U User -d Store"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s

  # --- Redis Service ---
  redis:
    image: redis:7.2-alpine
    container_name: redis_for_store
    ports:
      - "6379:6379" # Стандартний порт Redis
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # --- pgAdmin Service ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_for_store
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: new_password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

# --- Мережі та Volumes ---
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  redis_data: